name: Python CI with Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        pip install coverage

    - name: Run tests with coverage
      run: |
        # Prompt the user whether to run tests
        read -p "Do you want to run tests? (y/n): " choice
        if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
          coverage run -m unittest discover -s tests -p 'test_*.py'
        else
          echo "Tests skipped."
        fi

    - name: Generate coverage report
      run: |
        coverage report
        coverage xml

