name: Python CI with Coverage

on:
  push:
    paths:
      - 'src/**/*.py'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests -p 'test_*.py'

    - name: Generate coverage report
      run: |
        coverage report
        coverage xml


